server.port=8080

# Keycloak OAuth2 Configuration
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=${keycloakClientId}
spring.security.oauth2.client.registration.keycloak.client-secret=change-me
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloakUrl}/realms/${keycloakRealm}

# Vaadin
vaadin.launch-browser=true
